47 re estruturação do login
42rio-projects/ft_transcendence pull request #48
Opened 2024-02-25 22:56 UTC by dvargas1

Re-estruturei o login e efetivamente agora ele cria o usuário no banco e loga com base no banco, enviando para o menu.

estruturei minha maquina melhora para lidar com o .venv do python entao coloquei um .gitignore mais especifico de django

criei nosso requirements.txt para facilitar se alguem quiser configurar o venv na propria maquina.

###importante###
A ideia é reestruturar a sessão criando um app para o menu (puxar os dados do banco e preencher o menu, além de botao de logout) depois, cirar um app para o chat e um app para torneio, deixar o pong somente para o jogo.

2024-02-25 22:58 UTC, dvargas1 commented
Seria interessante, imagino eu, colocar o two factor também na app de login.

2024-02-26 19:13 UTC, gabrielclcardoso requested changes
Tudo perfeito, somente a questão do Daphne que acredito que deve quebrar funcionalidade do chat.

2024-02-26 19:13 UTC, gabrielclcardoso commented on django/ft_transcendence/settings.py
> +    # 'daphne',
O daphne é utilizado para a comunicação entre sockets do chat. O chat estava funcional sem o daphne instalado?

2024-02-27 11:36 UTC, dvargas1 commented on django/ft_transcendence/settings.py
> +    # 'daphne',
nao cheguei a testar o chat amigo, esqueci de descomentar ela, mb

2024-02-27 11:41 UTC, merged